[theme]
font = "Garamond"
headingFont = "Garamond"
codeFont = "monospace"
[theme.sidebar]
font = "Garamond"
headingFont = "Garamond"
codeFont = "monospace"

[client]
showSidebarNavigation = false


[server]
enableStaticServing = true